/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/about-site': RouteRecordInfo<'/posts/about-site', '/posts/about-site', Record<never, never>, Record<never, never>>,
    '/posts/english-writing-mydeream': RouteRecordInfo<'/posts/english-writing-mydeream', '/posts/english-writing-mydeream', Record<never, never>, Record<never, never>>,
    '/posts/english-writing-spring': RouteRecordInfo<'/posts/english-writing-spring', '/posts/english-writing-spring', Record<never, never>, Record<never, never>>,
    '/posts/godot': RouteRecordInfo<'/posts/godot', '/posts/godot', Record<never, never>, Record<never, never>>,
    '/posts/hexo': RouteRecordInfo<'/posts/hexo', '/posts/hexo', Record<never, never>, Record<never, never>>,
    '/posts/move-to-valaxy': RouteRecordInfo<'/posts/move-to-valaxy', '/posts/move-to-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/test': RouteRecordInfo<'/posts/test', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/tuxun-plugin': RouteRecordInfo<'/posts/tuxun-plugin', '/posts/tuxun-plugin', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
